-- Seed the first wave of domain reputations from the starter list.
-- A separate script imports the full ~100k-domain list at deploy time.

insert into public.domain_reputations (domain, tier, score, signals, source, last_assessed) values
  ('nytimes.com',            'high',   0.9, '{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('washingtonpost.com',     'high',   0.9, '{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('bbc.co.uk',              'high',   0.92,'{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('bbc.com',                'high',   0.92,'{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('theguardian.com',        'high',   0.88,'{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('reuters.com',            'high',   0.95,'{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('apnews.com',             'high',   0.95,'{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('ft.com',                 'high',   0.92,'{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('economist.com',          'high',   0.9, '{"mbfc":"high"}'::jsonb,      'bundled_seed', now()),
  ('nature.com',             'high',   0.95,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('science.org',            'high',   0.95,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('nejm.org',               'high',   0.97,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('thelancet.com',          'high',   0.97,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('bmj.com',                'high',   0.95,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('jamanetwork.com',        'high',   0.95,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('cell.com',               'high',   0.94,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('pnas.org',               'high',   0.95,'{"wiki":"reliable"}'::jsonb,  'bundled_seed', now()),
  ('nih.gov',                'high',   0.95,'{"gov":true}'::jsonb,         'bundled_seed', now()),
  ('cdc.gov',                'high',   0.95,'{"gov":true}'::jsonb,         'bundled_seed', now()),
  ('who.int',                'high',   0.92,'{"gov":true}'::jsonb,         'bundled_seed', now()),
  ('nhs.uk',                 'high',   0.93,'{"gov":true}'::jsonb,         'bundled_seed', now()),
  ('mayoclinic.org',         'high',   0.9, '{"medical":true}'::jsonb,     'bundled_seed', now()),
  ('clevelandclinic.org',    'high',   0.88,'{"medical":true}'::jsonb,     'bundled_seed', now()),
  ('gov.uk',                 'high',   0.95,'{"gov":true}'::jsonb,         'bundled_seed', now()),
  ('europa.eu',              'high',   0.92,'{"gov":true}'::jsonb,         'bundled_seed', now()),
  ('wikipedia.org',          'high',   0.85,'{"crowdsourced":true}'::jsonb,'bundled_seed', now()),
  ('en.wikipedia.org',       'high',   0.85,'{"crowdsourced":true}'::jsonb,'bundled_seed', now()),
  ('cnn.com',                'medium', 0.6, '{"mbfc":"medium"}'::jsonb,    'bundled_seed', now()),
  ('foxnews.com',            'medium', 0.55,'{"mbfc":"medium"}'::jsonb,    'bundled_seed', now()),
  ('msnbc.com',              'medium', 0.55,'{"mbfc":"medium"}'::jsonb,    'bundled_seed', now()),
  ('nypost.com',             'medium', 0.5, '{"mbfc":"medium"}'::jsonb,    'bundled_seed', now()),
  ('dailymail.co.uk',        'medium', 0.45,'{"mbfc":"medium"}'::jsonb,    'bundled_seed', now()),
  ('medium.com',             'medium', 0.5, '{"user_generated":true}'::jsonb,'bundled_seed', now()),
  ('substack.com',           'medium', 0.5, '{"user_generated":true}'::jsonb,'bundled_seed', now()),
  ('reddit.com',             'medium', 0.5, '{"user_generated":true}'::jsonb,'bundled_seed', now()),
  ('infowars.com',           'low',    0.1, '{"mbfc":"low"}'::jsonb,       'bundled_seed', now()),
  ('naturalnews.com',        'low',    0.1, '{"mbfc":"low"}'::jsonb,       'bundled_seed', now()),
  ('zerohedge.com',          'low',    0.2, '{"mbfc":"low"}'::jsonb,       'bundled_seed', now()),
  ('rt.com',                 'low',    0.15,'{"mbfc":"low"}'::jsonb,       'bundled_seed', now()),
  ('sputniknews.com',        'low',    0.15,'{"mbfc":"low"}'::jsonb,       'bundled_seed', now()),
  ('mercola.com',            'low',    0.1, '{"mbfc":"low"}'::jsonb,       'bundled_seed', now())
on conflict (domain) do nothing;
